### ISSUE TITLE
error at demo launch

### ISSUE THREAD

**Issue by Cdk29** [mcvidomi/ML2Motif#1]
Hi !

I have cloned the git repository and tried to run the demo.py that you ship with the repository. However, when I launch it I get the following error :

LOAD/READ DATA
LOAD/READ DATA --- DONE!
TRAIN SVM
['/opt/shogun/lib/python2.7/dist-packages/shogun']
Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    Cobj.train(C=1.)
  File "/tmp/ML2Motif/SVM.py", line 75, in train
    self.ma = compute_poims(self.svm, self.kernel, 7, self.L)
  File "/tmp/ML2Motif/poim.py", line 43, in compute_poims
    (poim, max_poim, diff_poim) = reshape_normalize_contribs(poim, poimdegree, max_len)
  File "/tmp/ML2Motif/poim.py", line 122, in reshape_normalize_contribs
    A=numpy.abs(Contribs[k-1][numpy.floor(km/4),l]);
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
python demo.py  79.77s user 0.63s system 261% cpu 30.753 total

**Comment by mcvidomi** [comment]
Hi, 
the problem was a float instead of an integer access to a matrix element. Now, it should work.
Please try again :-)

**Comment by Cdk29** [comment]
Sorry for the delay of reply :) I will try it as soon I have some times, so this week I hope :-) and try it on some biological data.
